AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Api Gateway Template for test locally - GAMERLINK
  
Globals:
  Function:
    Timeout: 3000

Resources:
  GamerLink:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Suscriptions:
          Type: Api
          Properties:
            Path: /
            Method: any
